#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap           8 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave-browser desktop='^2'
bspc rule -a megasync state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# exec stuff

$HOME/.config/polybar/launch.sh
#picom  &
nitrogen --restore &
nm-applet &
cbatticon &
megasync &

alttab -d 2 -w 1 -fg '#d0d0d0' -bg "#4b4b4b" -frame "#ffaf00" -t 128x125 -i 127x64 -font "xft:Fira Sans Book-9" &

